---
title: "구로구와 영등포구 미세먼지 분석"
output: html_document
---
구로구와 영등포구 미세먼지 분석 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(foreign)#foreign 패키지 설치 (spss, sas, stata 등 통계분석 s/w)
library(dplyr)
library(ggplot2)
library(readxl)
library(treemap)
library(ggiraphExtra)
library(tibble)
library(maps)
library(mapproj)
library(ggmap)
library(stringr)
library(grid)
library(leaflet)
library(KoNLP)
library(rJava)
library(corrplot)
library(psych)
library(plotly)

```


 
## 미세먼지 데이터 분석

### 데이터를 가져와 구로구와 영등포구로 필터링 하기
```{r road, filter data, echo=FALSE}


setwd("C:/Rstudy/work_R")

dustdata <- read_excel("DATA/dustdata.xlsx")


dust_anal <- dustdata %>% 
  filter(area %in% c("구로구","영등포구"))
dust_anal



```

```{r count, subset}
count(dust_anal, yyyymmdd) %>% arrange(desc(n))
count(dust_anal, area) %>% arrange(desc(n))

dust_anal_area_gr <- subset(dust_anal, area == "구로구")
dust_anal_area_yu <- subset(dust_anal, area == "영등포구")
```


## 정제된 데이터 기반으로 그래프 그리기 

### BOXPLOT
```{r boxplot, ggplot}
boxplot(dust_anal_area_gr$finedust, dust_anal_area_yu$finedust,
        main = "finedust_compare", xlab = "AREA", names = c("구로구","영등포구"),
        ylab = "FINEDUST_PM", col = c("blue","green"))

```

### GGPLOT
```{r ggplot}
gg <- ggplot(dust_anal, aes(area, finedust)) +
  geom_boxplot(fill = c("green", "blue"))
plotly::ggplotly(gg)

```

### GGPLOT 산점도 
```{r point-plot}
point <- ggplot(dust_anal, aes(x=yyyymmdd, y =finedust, col = area)) +geom_point()
ggplotly(point)
```

### t-test 수행 
```{r t-test}
t.test( data = dust_anal, finedust~ area, var.equal = T)
```





