---
title: "E22 R Markdown으로 데이터 분석"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(foreign)#foreign 패키지 설치 (spss, sas, stata 등 통계분석 s/w)
library(dplyr)
library(ggplot2)
library(readxl)
library(treemap)
library(ggiraphExtra)
library(tibble)
library(maps)
library(mapproj)
library(ggmap)
library(stringr)
library(grid)
library(leaflet)
library(KoNLP)
library(rJava)
library(corrplot)
library(psych)

```

## R Markdown



문자 앞뒤에 *특수 문자*를 넣으면 기울임체가 됩니다. 
 
문자 앞뒤에 **특수 문자**를 넣으면 강조체가 됩니다. 
 
문자 앞뒤에 ~~특수 문자~~를 넣으면 취소선을 만듭니다. 
 
문자 앞뒤에 [특수 문자](http://www.google.com/search?q=special+character)를 넣으면 하이퍼 링크를 만듭니다. 
 
## Including Plots

여기서 부터 *그래프*입니다.


```{r dustdata, echo=FALSE}


setwd("C:/Rstudy/work_R")

dustdata <- read_excel("DATA/dustdata.xlsx")


dust_anal <- dustdata %>% 
  filter(area %in% c("구로구","영등포구"))
dust_anal

count(dust_anal, yyyymmdd) %>% arrange(desc(n))
count(dust_anal, area) %>% arrange(desc(n))

dust_anal_area_gr <- subset(dust_anal, area == "구로구")
dust_anal_area_yu <- subset(dust_anal, area == "영등포구")
boxplot(dust_anal_area_gr$finedust, dust_anal_area_yu$finedust,
        main = "finedust_compare", xlab = "AREA", names = c("구로구","영등포구"),
        ylab = "FINEDUST_PM", col = c("blue","green"))

gg <- ggplot(dust_anal, aes(area, finedust)) +
  geom_boxplot(fill = c("green", "blue"))
plotly::ggplotly(gg)

```



