---
title: "어플리케이션 요구사항 분석 시험 김준연 시험 답지"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
library(treemap)
library(ggiraphExtra)
library(tibble)
library(maps)
library(mapproj)
library(ggmap)
library(stringr)
library(grid)
library(leaflet)
library(KoNLP)
library(rJava)
library(moments)
library(Hmisc)
library(prettyR)
library(MASS)
library(gmodels)
setwd("C:/Rstudy/Work_R")
```

##  

# 1. 거주지역별 빈도수를 구하세요 
```{r cars}
test <- read.csv("4_test_data1.csv")
table(test$resident2)


```

## 2. 성별 빈도수를 구하세요 


```{r cars2}


table(test$gender2)
```



## 3 .성별에 따른 거주지역의 분포를 시각화 하여 나타내 보세요 
```{r pressure, warning=FALSE}
gg1<-ggplot(test, aes(x=test$gender2 , fill = test$resident2))+geom_bar(position = "dodge") +
  coord_flip()
plotly::ggplotly(gg1)
```


## 4. 거주지역에 따른 성별 분포 현황을 시각화하여 나타네 보세요 

```{r pressure2, warning=FALSE}
gg2<-ggplot(test, aes(x=test$resident2 , fill = test$gender2))+geom_bar(position = "dodge") +
  coord_flip()
plotly::ggplotly(gg2)
```

## 5. 직종별 나이 분포 현황을 출력해 보세요

```{r pressure3, warning=FALSE}
gg2<-ggplot(test, aes(x=test$age , fill = test$job2, type = "l"))+geom_bar(position = "dodge") 
plotly::ggplotly(gg2)
```

